import type { NextPage } from 'next';
import Head from 'next/head';
import Calendar from '../components/calendar';
import MainPage from '../components/MainPage/MainPage';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Calendar />
        </>
    );
};

export default Home;
